on:
  push:
    branches:
      - master
      - dev

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x

      - name: Run dotnet test
        run: cd tests && dotnet test
        env:
          PG_CONN: ${{ secrets.PG_CONN }}
